/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.si3e;

/**
 *
 * @author Client-34
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState (MAXIMIZED_BOTH);
        setTitle ("Aop SI3E");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mni_keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mni_pembeli = new javax.swing.JMenuItem();
        mni_produk = new javax.swing.JMenuItem();
        mni_detaiProduk = new javax.swing.JMenuItem();
        mni_transaksi = new javax.swing.JMenuItem();
        mni_pembayaran = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mni_keluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mni_keluar.setText("Keluar");
        mni_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_keluarActionPerformed(evt);
            }
        });
        jMenu1.add(mni_keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data");

        mni_pembeli.setText("Pembeli");
        mni_pembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_pembeliActionPerformed(evt);
            }
        });
        jMenu3.add(mni_pembeli);

        mni_produk.setText("Produk");
        mni_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_produkActionPerformed(evt);
            }
        });
        jMenu3.add(mni_produk);

        mni_detaiProduk.setText("Detail Produk");
        mni_detaiProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_detaiProdukActionPerformed(evt);
            }
        });
        jMenu3.add(mni_detaiProduk);

        mni_transaksi.setText("Transaksi");
        mni_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_transaksiActionPerformed(evt);
            }
        });
        jMenu3.add(mni_transaksi);

        mni_pembayaran.setText("Pembayaran");
        mni_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_pembayaranActionPerformed(evt);
            }
        });
        jMenu3.add(mni_pembayaran);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mni_keluarActionPerformed

    private void mni_pembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_pembeliActionPerformed
        // TODO add your handling code here:
        Fpembeli fp=new Fpembeli();
        fp.setTitle ("Form Pembeli");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_mni_pembeliActionPerformed

    private void mni_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_produkActionPerformed
        // TODO add your handling code here:
        Produk fp=new Produk();
        fp.setTitle ("Form produk");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_mni_produkActionPerformed

    private void mni_detaiProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_detaiProdukActionPerformed
        // TODO add your handling code here:
        DetailProduk fp=new DetailProduk();
        fp.setTitle ("Form DetailProduk");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_mni_detaiProdukActionPerformed

    private void mni_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_transaksiActionPerformed
        // TODO add your handling code here:
        Transaksi fp=new Transaksi();
        fp.setTitle ("Form Transaksi");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_mni_transaksiActionPerformed

    private void mni_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_pembayaranActionPerformed
        // TODO add your handling code here:
        Pembayaran fp=new Pembayaran();
        fp.setTitle ("Form Pembayaran");
        fp.setVisible(true);
        jDesktopPane1.add(fp);
    }//GEN-LAST:event_mni_pembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mni_detaiProduk;
    private javax.swing.JMenuItem mni_keluar;
    private javax.swing.JMenuItem mni_pembayaran;
    private javax.swing.JMenuItem mni_pembeli;
    private javax.swing.JMenuItem mni_produk;
    private javax.swing.JMenuItem mni_transaksi;
    // End of variables declaration//GEN-END:variables
}
