/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.si3e;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class Transaksi extends javax.swing.JInternalFrame {
    public void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
     
        model.addColumn("Id Transaksi");
        model.addColumn("Id Barang");
        model.addColumn("Kode Barang");
        model.addColumn("Id Pembeli");
        model.addColumn("Tanggal");
        model.addColumn("Keterangan");
        
        try{
            int no = 1; 
            String sql = "Select * From transaksi";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
                        
                tabel3.setModel(model);
            }
        }catch(SQLException e){
            System.out.println("Error :" +e.getMessage());
            
        }
    }
    
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        lbl_judul = new javax.swing.JLabel();
        lbl_transakasi = new javax.swing.JLabel();
        lbl_idbarang = new javax.swing.JLabel();
        lbl_idpembeli = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JLabel();
        lbl_keterangan = new javax.swing.JLabel();
        lbl_kodebarang = new javax.swing.JLabel();
        txt_transaksi = new javax.swing.JTextField();
        txt_idbarang = new javax.swing.JTextField();
        txt_idpembeli = new javax.swing.JTextField();
        txt_kdbarang = new javax.swing.JTextField();
        txt_keterangan = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel3 = new javax.swing.JTable();
        txt_tgl1 = new com.toedter.calendar.JDateChooser();

        jTextField7.setText("jTextField7");

        setClosable(true);
        setIconifiable(true);
        setTitle("Entry Transaksi");

        lbl_judul.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_judul.setText("Form Transaksi ");

        lbl_transakasi.setText("ID Transaksi");

        lbl_idbarang.setText("ID Barang");

        lbl_idpembeli.setText("ID Pembeli");

        txt_tgl.setText("Tanggal");

        lbl_keterangan.setText("Keterangan");

        lbl_kodebarang.setText("Kode barang ");

        txt_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_transaksiActionPerformed(evt);
            }
        });

        txt_idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idbarangActionPerformed(evt);
            }
        });

        txt_kdbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kdbarangActionPerformed(evt);
            }
        });

        btn_Save.setText("Add");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_cancel.setText("Clear");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        tabel3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btn_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_transakasi)
                                        .addComponent(lbl_idbarang))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_idbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(txt_transaksi))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                    .addComponent(lbl_kodebarang)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_kdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lbl_idpembeli)
                                            .addGap(27, 27, 27))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_tgl)
                                            .addGap(39, 39, 39)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_tgl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_idpembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_keterangan)
                                .addGap(18, 18, 18)
                                .addComponent(txt_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_judul)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lbl_judul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_transakasi)
                    .addComponent(txt_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_kodebarang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idbarang)
                    .addComponent(txt_idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idpembeli)
                    .addComponent(txt_idpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_tgl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_keterangan)
                            .addComponent(txt_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Save)
                            .addComponent(btn_update)
                            .addComponent(btn_cancel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_tgl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_transaksiActionPerformed

    private void txt_idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idbarangActionPerformed

    private void txt_kdbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kdbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kdbarangActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
    //Edit Data
    String tampilan = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
    String tanggal = String.valueOf(fm.format(txt_tgl1.getDate()));
        try{             
            String sql = "UPDATE transaksi set Id_barang='"+txt_idbarang.getText()+"',"
                        +"kode_barang='"+txt_kdbarang.getText()+"',"
                        +"Id_pembeli='"+txt_idpembeli.getText()+"',"
                        +"Tanggal='"+tanggal+"',"
                        +"Keterangan='"+txt_keterangan.getText()+"'"
                        +"where Id_transaksi='"+txt_transaksi.getText()+"'";
            java.sql.Connection con = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Edit Data Gagal");
        }
        tampilkan_data();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
    // Membersihkan Input
        txt_transaksi.setText(null);
        txt_idbarang.setText(null);
        txt_kdbarang.setText(null);
        txt_idpembeli.setText(null);
        txt_tgl1.setDate(null);
        txt_keterangan.setText(null);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
    // Tambah Data
    String tampilan = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
    String tanggal = String.valueOf(fm.format(txt_tgl1.getDate()));
        try{
            String sql = "INSERT INTO transaksi(Id_barang,kode_barang,Id_pembeli,Tanggal,Keterangan) VALUES ('"+txt_idbarang.getText()+"','"+txt_kdbarang.getText()+"','"+txt_idpembeli.getText()+"','"+tanggal+"','"+txt_keterangan.getText()+"')";
            java.sql.Connection con = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Simpan Data Berhasil");
            
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, "Simpan Data Gagal");
        }
        tampilkan_data();
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void tabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel3MouseClicked
    //Klik Tabel
        int baris = tabel3.rowAtPoint(evt.getPoint());
        
        String Id_transaksi = tabel3.getValueAt(baris, 0).toString();
        txt_transaksi.setText(Id_transaksi);
        
        String Id_barang = tabel3.getValueAt(baris, 1).toString();
        txt_idbarang.setText(Id_barang);
        
        String kode_barang = tabel3.getValueAt(baris, 2).toString();
        txt_kdbarang.setText(kode_barang);
        
        String Id_pembeli = tabel3.getValueAt(baris, 3).toString();
        txt_idpembeli.setText(Id_pembeli);
        
        try {
            DefaultTableModel model = (DefaultTableModel)tabel3.getModel();
            int index = tabel3.getSelectedRow();
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(baris, 4));
            txt_tgl1.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String Keterangan = tabel3.getValueAt(baris, 5).toString();
        txt_keterangan.setText(Keterangan);
        
    }//GEN-LAST:event_tabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lbl_idbarang;
    private javax.swing.JLabel lbl_idpembeli;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_keterangan;
    private javax.swing.JLabel lbl_kodebarang;
    private javax.swing.JLabel lbl_transakasi;
    private javax.swing.JTable tabel3;
    private javax.swing.JTextField txt_idbarang;
    private javax.swing.JTextField txt_idpembeli;
    private javax.swing.JTextField txt_kdbarang;
    private javax.swing.JTextField txt_keterangan;
    private javax.swing.JLabel txt_tgl;
    private com.toedter.calendar.JDateChooser txt_tgl1;
    private javax.swing.JTextField txt_transaksi;
    // End of variables declaration//GEN-END:variables
}
